### ISSUE TITLE
Some thoughts on sph-sc

### ISSUE THREAD

**Issue by bentxt** [sph-mn/sph-sc#2]
Hi,
SC finally runs on my machine, but the whole installation process was pretty annoying, which I make Guile responsible for. I received great support from the creator of 'sc, but still, the process took time and during this time I had the opportunity to reflect why I so desperately want to install that exotic software. 

Especially when I consider the fact, that I already installed 'sc' earlier some month ago, maybe even years. When I remember correctly I was not convinced of the sc compiler because of its weak macro support. Now that I see multiple references on that in project, I'd like to make a new try. And in addition to that I find it encouraging that sc is still in active development, because I think it is the only compiler that I know of that is happy with just providing some thin layer of syntactic sugar for the target language. Because that's it what I'm looking for a start. And then I hope for a capable macro system.
Sorry for misusing the 'issues' section as message board.
Ben

**Comment by sph-mn** [comment]
hi and thanks for the feedback. a thin layer over the target language without adding helper code to the output or providing substantial code-generating abstractions ist just what sc is supposed to be. if there are opportunities to make the implementation smaller or the resulting c code more like hand-written, im looking towards taking them. there are some example macros [here](https://raw.githubusercontent.com/sph-mn/sph-sc/master/other/example-macros.sc) but it might be better to just go from the examples in the readme. anyway, if anything particular seems missing from the macro system or not working as expected, i'd be happy to know.
