### ISSUE TITLE
Initialize int variable in declaration

### ISSUE THREAD

**Issue by arunisaac** [sph-mn/sph-sc#4]
Hi,

I would like to initialize an int variable in its declaration, like `int n = 1`. Currently, I can only do this with two forms---a declare and a set---like so

```scheme
(declare n int)
(set n 1)
```

Is there some way to do this with just a declare form---something like `(declare n (int 1))`?

Thanks!

**Comment by sph-mn** [comment]
hi, 

yes, there is a way - with `define`.

~~~
(define n int 1)
~~~

**Comment by arunisaac** [comment]
Thanks, I somehow missed that in the documentation. I also just found `let*` which is useful in some other occasions.

Cheers!
