### ISSUE TITLE
Negation bug

### ISSUE THREAD

**Issue by arunisaac** [sph-mn/sph-sc#5]
Hi,

Negation doesn't seem to work correctly. `(- (+ x y))` gets translated to `((x+y));`. Notice the missing negation.

Cheers!

**Comment by tsequitur** [comment]
hi,

that is interesting, thank you for the report.
i will look into it as soon as possible. i dont see a reason why this should not work, so it can be fixed. 

regards

**Comment by sph-mn** [comment]
hi,

that is interesting, thank you for the report.
i will look into it as soon as possible. i dont see a reason why this should not work, so it can be fixed.

regards

**Comment by sph-mn** [comment]
hi, 
it should be fixed now in the current version of the code. 
 (- (+ x y)) becomes (-(x+y)). same when using + instead.
hope that helps.

**Comment by arunisaac** [comment]
It works now. Thanks!

**Comment by arunisaac** [comment]
There's a similar bug for unary division. `(/ 2)` should get translated to `(1/2)`, but it gets translated to `(2)`. Could you fix this one too? Thanks!

**Comment by sph-mn** [comment]
it is now implemented. just for the record, it doesnt seem to be a feature of c.

**Comment by arunisaac** [comment]
It works, thanks! :-)

Yes, unary division is not a feature of C. But it's a scheme feature, and a very natural thing when one is writing C in a scheme-like syntax.
