### ISSUE TITLE
1+ and 1-

### ISSUE THREAD

**Issue by arunisaac** [sph-mn/sph-sc#6]
`echo '(* 10 (1+ 2))' | sc` returns `(10*1+(2));` As you can see, this is a bug. There's a similar problem with 1- as well. I understand that the 1+ and 1- functions don't exist in sph-sc. But, it would be good to raise an error if they are used. The error checking can be based on the fact that C function names can only start with an alphabetic character.

Another way, and I think the better way, is to simply implement 1+ and 1- as macros. 1+ and 1- are not supported by C, but they are so common in scheme and are handy to have.

Cheers!

**Comment by sph-mn** [comment]
hi and thanks for the message. i will add 1+ and 1- to sc soon.

**Comment by arunisaac** [comment]
Also, when and unless would be very convenient to have. C is full of
such side-effect oriented statements, and using cond every time is
rather verbose.

Thanks!

**Comment by sph-mn** [comment]
thanks for the suggestions. all four forms have been added. hope everything works as expected.

**Comment by arunisaac** [comment]
Works beautifully, thank you!
